image:
  repository: teslamate/teslamate
  tag: 3.0.0@sha256:6569026b73bd657455bbec05965d07fa30b6d4d70eaab0bd5b343231c0429167
  pullPolicy: IfNotPresent
mqtt:
  enabled: true
  host: "" # set in CLI
  username: "" # set in CLI
  password: "" # set in CLI
database:
  host: postgresql
  name: teslamate
  username: teslamate
  password: "" # set in CLI
encryptionKey: "" # set in CLI
resources:
  requests:
    cpu: 30m
    memory: 350Mi
  limits:
    memory: 350Mi
