image:
  repository: ghcr.io/stirling-tools/stirling-pdf
  tag: 2.0.2@sha256:af9942975d39b953a008aaa1bb2bbb23330d725d8aeda835eb53de3715e42e36
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
maxSize: 500m
