image:
  repository: ghcr.io/stirling-tools/stirling-pdf
  tag: 2.3.1@sha256:8fb811bce906513dc5dd312981f070e4780e02da20b7a20327d6e141077532f5
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
maxSize: 500m
