image:
  repository: ghcr.io/stirling-tools/stirling-pdf
  tag: 2.2.1@sha256:bba1cf9fa7f6b298b7417fd39f5441552ddb815c5c7452ceaf3042fd963646e3
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
maxSize: 500m
