image:
  repository: ghcr.io/stirling-tools/stirling-pdf
  tag: 2.4.4@sha256:c08373b5980696ae188a67f68f66e40742f2475280f546e3dbb39953e5e1e883
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
maxSize: 500m
