image:
  repository: ghcr.io/stirling-tools/stirling-pdf
  tag: 2.4.6@sha256:073023f9829b96a5e64ec3cdbf2f441e65feb8b89bfbebeae217b96564b546e9
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
maxSize: 500m
