image:
  repository: ghcr.io/stirling-tools/stirling-pdf
  tag: 2.4.1@sha256:99e82be32a8bc70e99f284f5b2e1be582be05f7410e3707932fce973b0678419
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
maxSize: 500m
