image:
  repository: ghcr.io/stirling-tools/stirling-pdf
  tag: 2.1.5@sha256:e8b96ebd749ee6c087f853c31fbbb79dc35bb08792bdd5ef0e72e74f5b209ea1
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
maxSize: 500m
