image:
  repository: ghcr.io/stirling-tools/stirling-pdf
  tag: 2.1.4@sha256:940c83732d373b08efd110de708d51d639705404de7dabc7230e5665819efb4a
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
maxSize: 500m
