image:
  repository: ghcr.io/stirling-tools/stirling-pdf
  tag: 2.0.3@sha256:8bb1bb58806c549c211ac64a8a846b39d0b2e029a6549a60ec54664333b8b833
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
maxSize: 500m
