image:
  repository: ghcr.io/stirling-tools/stirling-pdf
  tag: 2.1.0@sha256:56dd735b7b59ca4fe69266f6f1933cd4e1c203ac46f0886845c4d5fc1bc65cf1
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
maxSize: 500m
