image:
  repository: ghcr.io/stirling-tools/stirling-pdf
  tag: 2.1.2@sha256:12395ebbdb5d85b58f3e7db0c22afc593863b97f1afe4561de8cd8b0325a3c09
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
maxSize: 500m
