image:
  repository: ghcr.io/stirling-tools/stirling-pdf
  tag: 2.4.2@sha256:5866b6632dd99c28d45edcb6e984260981efa0f9976e8d3d0c9f35d196a347c5
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
maxSize: 500m
