image:
  repository: ghcr.io/c4illin/convertx
  tag: v0.16.0@sha256:2397d94fa091e48f1fbfcb97dd28d6c36cf7bdac2a33fb5cd66813e6ab723849
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
autoDeleteEveryNHours: 1
maxSize: 500m
