image:
  repository: ghcr.io/c4illin/convertx
  tag: v0.16.1@sha256:1402221b314c794e918a219b7f7698a214e447304472ca406acccc91e9537e63
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
autoDeleteEveryNHours: 1
maxSize: 500m
