image:
  repository: ghcr.io/c4illin/convertx
  tag: v0.17.0@sha256:e1f85be04bbaf8a55ead9261194c3ae0fa0957d303ea537127154860b2552afd
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
autoDeleteEveryNHours: 1
maxSize: 500m
