name: ConvertX

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - 'kubernetes/charts/convertx/**'
      - '.github/workflows/convertx.yaml'

jobs:
  deploy-convertx:
    name: Deploy ConvertX
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Connect to Kubernetes
        uses: ./.github/actions/connect-k8s
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          hostname: kubernetes-api.${{ vars.HOST }}
          serviceTokenId: ${{ vars.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_ID }}
          serviceTokenSecret: ${{ secrets.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_SECRET }}

      - name: Install convertx
        run: |
          helm dependency update .
          helm upgrade --install --wait --atomic --debug \
            convertx . \
            --namespace default \
            -f values.yaml \
            --set ingress.host="convert.${{ vars.HOST }}" \
            --set jwtSecret="${{ secrets.CONVERTX_JWT_SECRET }}" \
            --set auth.username="${{ vars.CONVERTX_USERNAME }}" \
            --set auth.password="${{ secrets.CONVERTX_PASSWORD }}"
        working-directory: kubernetes/charts/convertx

      - name: Disconnect from Kubernetes
        if: always()
        uses: ./.github/actions/disconnect-k8s