name: Plex

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - 'kubernetes/charts/plex/**'
      - '.github/workflows/plex.yaml'

jobs:
  deploy-plex:
    name: Deploy Plex
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Connect to Kubernetes
        uses: ./.github/actions/connect-k8s
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          hostname: kubernetes-api.${{ vars.HOST }}
          serviceTokenId: ${{ vars.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_ID }}
          serviceTokenSecret: ${{ secrets.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_SECRET }}

      - name: Install plex
        run: |
          helm dependency update .
          helm upgrade --install --wait --atomic --debug \
            plex . \
            --namespace default \
            -f values.yaml
        working-directory: kubernetes/charts/plex

      - name: Disconnect from Kubernetes
        if: always()
        uses: ./.github/actions/disconnect-k8s